# Module 4 Outbreak Analysis

Author: Finlay Maguire 
Last Modified: November 11, 2025

## Lecture

Link to PDF of slides from google

## Lab

1. [Background](#intro)
2. [Setup](#setup)
3. [Cluster Identification](#cluster)
4. [SNP Analysis](#snp)
5. [Transmission Inference](#trans)

In this lab practical we will be using microbial genomes (and associated contextual metadata) to investigate a suspected nosocomial (hospital-acquired) outbreak of *Methicillin resistance Staphylococcus aureus* (MRSA) in a UK-based Neonatal Intensive Care Unit (NICU).  The data we are using comes from a classic study which demonstrated the utility of whole genome sequencing for investigating an MRSA outbreak within a Special Care Baby Unit (also known as a NICU) of the Cambridge University Hospitals NHS Foundation Trust (CUH).

> Harris SR, Cartwright EJP, Török ME, et al. Whole-genome sequencing for analysis of an outbreak of methicillin-resistant Staphylococcus aureus: a descriptive study. *Lancet Infect Dis* 2012 [10.1016/S1473-3099(12)70268-2](http://dx.doi.org/10.1016/S1473-3099\(12\)70268-2)

This practical will step you through the genomic components of a typical nosocomial bacterial outbreak investigation, specifically:

- Identifying potential outbreak clusters
- Determining SNP distances
- Inferring outbreak phylogenies
- Performing transmission inference

<a name="intro"></a>

### Background

*Staphylococcus aureus* is a Gram-positive coccoidal bacteria that forms a normal commensal member of the microbiome in 20-40% of people ([Karsten, 2017](https://doi.org/10.1016/j.ijmm.2016.11.007)). However, when skin and mucosal barriers are disrupted (e.g., through medical procedures such as catheterisation, tracheal tubes, surgeries) *S. aureus* can cause opportunistic invasive infections ([Lee, 2018](https://doi.org/10.1038/nrdp.2018.33)).   

Since the 1960s, variants have emerged and spread globally that are resistant to the majority of β-lactam antibiotics through the independent acquisitions of the staphylococcal cassette chromosome mec (SCCmec) ([IWG-SSC, 2009](https://doi.org/10.1128/AAC.00579-09).  This combination of commensal carriage, antimicrobial resistance, and healthcare-associated infection opportunities (along with additional virulence factors) have led to MRSA becoming a leading cause of hospital-associated mortality and morbidity globally ([GBD, 2024](https://doi.org/10.1016/s0140-6736(24)01867-1)). Therefore, tracking and preventing MRSA outbreaks is a major priority for infection prevention and control (IPAC or IPC) within hospital settings especially within the NICU due to the vulnerability of immunocompromised preterm infants and the high frequency of invasive procedures.
This has led to adoption of genomic epidemiological approaches to detect MRSA outbreaks and track transmission links not apparent from traditional approaches alone ([Blane, 2024](https://doi.org/10.1099/mgen.0.001235)). These sort of outbreak investigations are generally led by the infection prevention & control (IPAC or IPC) team in a clinical setting or by the relevant public health team depending on the suspected infection source, geographic scale, and regional resource availability (e.g., Public Health Agency of Canada/Canadian Food Inspection Agency or provincial bodies like Public Health Ontario). 

Within the SCBU/NICU of Cambridge University Hopitals NHS Trust (and most hospitals) all inpatients are screened for MRSA carriage upon admission and once per week thereafter using culture-based or nucleic-acid based test. Specific IPAC policies and guidelines will determine criteria for initiating an outbreak investigation (e.g., a certain number of positive screens within a specific time and/or location).  

Routine surveillance has identified that 3 infants within the SCBU/NICU (P11-P13) are positive for MRSA carriage at the same time. Isolates from these 3 infants have also been shown to have the same pattern of antibiotic resistances. The IPAC team has therefore been activated to further investigate this as a suspected outbreak in the SCBU/NICU at CUH. 
They have performed a systematic review of all MRSA isolates from the SCBU/NICU over the preceding 6-12 months and identified a series of overlapping MRSA carriages with this same set of resistances. Due to multi-week gaps in the positive SCBU/NICU isolates they have also collected potentially matching MRSA isolates from parents and the wider hospital/community.  To gain better insight into this potential outbreak and identify which of these isolates are linked by direct transmission chains, CUH have sequenced these isolates using 150bp paired-end reads via an Illumina MiSeq platform.

**You are a clinical bioinformatician who has been asked to support the investigation and analyses these genomes**

<a name="setup"></a>

### Set-Up

This lab practical will involve running the following software:

* [mlst](https://github.com/tseemann/mlst)
* [poppunk](https://github.com/bacpop/PopPUNK)
* [SKA](https://github.com/bacpop/ska.rust)
* [gubbins](https://github.com/nickjcroucher/gubbins)
* [iqtree](https://github.com/iqtree/iqtree3)
* [treetime](https://github.com/xavierdidelot/BactDating)
* [transphylo](https://github.com/xavierdidelot/TransPhylo)

:::: {.callout type="blue" style="subtle" title="Note: Bioinformatics in Practice" collapsible="true"}

Typically, most of these analyses would be run using a workflow such as [bactopia](https://bactopia.github.io/latest/) that you are confident will reproducibly generate validated and verified outputs (ideally as part of your institution's ISO15189 accreditation or equivalent).  We will run the tools directly today so you get insight into what these workflows are actually doing!

::::

#### Data

Using ssh connect to the provided analysis server instance:

```bash
ssh -i YOUR_KEY.pem YOUR_USER@XX.uhn-hpc.ca
```

Now create a folder in your `~/workspace` and copy/link over the files you will need:

```bash
mkdir -p ~/workspace/module4
cd ~/workspace/module4
cp -r ~/CourseData/module4/contextual_data.csv  ~/CourseData/module4/SASCBU26_reference.fna .
ln -s ~/CourseData/module4/assemblies .
```
:::: {.callout type="blue" style="subtle" title="Note: Contextual Data 'Interpolation'" collapsible="true"}

Specific collection dates were not available so have been inferred based on relative sampling gaps

::::

When you are finished with these steps you should be inside your work directory `~/workspace/module4`. You can verify this by running the command `pwd`.

**Output after running `pwd`**

```bash
~/workspace/module4
```

You now see an `assemblies/` folder in the current directory along with a `contextual_metadata.tsv` (all the contextual data needed for this analysis) and `SASCBU26_reference.fna` (the reference genome we will use later):

**Output after running `ls`**

```bash
SASCBU26_reference.fna  assemblies  contextual_data.csv
```

#### Activate environment

Next we will activate the pre-installed [conda](https://docs.conda.io/en/latest/) environment, which will have all the tools needed by this tutorial pre-installed. To do this please run the following:

**Commands**
```bash
conda activate outbreak
```

You should see the command-prompt (where you type commands) switch to include `(outbreak)` at the beginning, showing you are inside this environment. You should also be able to run the `mlst` command like `mlst --version` and see output:

**Output after running `mlst --version`**
```bash
mlst 2.23.0
```

#### Find your IP address

Similar to yesterday, we will want to either use the assigned hostname (e.g., xx.uhn-hpc.ca where xx is your instance number) or find the IP address of your machine on AWS so we can access some files from your machine on the web browser. To find your IP address you can run:

**Commands**
```bash
curl http://checkip.amazonaws.com
```

This should print a number like XX.XX.XX.XX. Once you have your address, try going to <http://xx.uhn-hpc.ca> or <http://IP-ADDRESS> and clicking the link for **module4**. This page will be referred to later to easily download/view some of our output files. 

<a name="cluster"></a>

### Cluster Identification

All isolates that are putatively linked to the outbreak have been done so on the basis of time, location, and phenotype (specifically antibiotic susceptibilities). However, just because 2 isolates have the same resistance pattern does not mean they are closely related. 
Although this is a relatively small set of isolates we are often evaluating very large numbers of genomes for their potential connection to an outbreak.
Additionally, most downstream outbreak analyses (such as transmission inference) perform best when applied to as little diversity as possible (i.e., just genomes from a single outbreak event).

This means our first task is to identify and group which isolates are actually connect


are likely to be linked using the sort of typing methods you encountered in the previous lab practical.
This helps us to eliminate unrelated genomes and determine whether 1 or more outbreaks are likely to be taking place.

To make things faster for this practical, we have provided pre-inferred genome assemblies (generated using [shovill](https://github.com/tseemann/shovill) with the [skesa](https://github.com/ncbi/SKESA) assembler).

You can infer the 7-gene MLST using the [pubMLST *Staphylococcus aureus* scheme](https://pubmlst.org/organisms/staphylococcus-aureus) by running the `mlst` tool on each of the genome assemblies.

```bash
mkdir -p outbreak_cluster_identification; cd outbreak_cluster_identification
mlst --scheme saureus ../assemblies/\*.fa > mlst.tsv
```

Now download the `mlst.tsv` output file (using either `scp` or the IP address listed above) and open it in your tabular data tool of choice (e.g., pandas/python, R, excel).

**Based on these results, which genomes do you suspect may not be part of this outbreak?**

:::: {.callout type="green" title="Answer" collapsible="true"}

P27 & P28 have different MLSTs to any other genome, P29, 34-38 (with P37 a partial match) could be an ST22 outbreak, P30-33 could be an ST772 outbreak, and the rest all belonging to this large ST2731 grouping

::::

However, MLST is only 7 genes so we are leaving lots of information on the table using just MLST.  

**Why might genomes with a different MLST still be closely related or those with the same MLST be relatively unrelated?**

:::: {.callout type="green" title="Answer" collapsible="true"}

MLST are only 7 genes so a small amount of mutation (or conservation!) in just these genes can lead to a totally different MLST - schemes are designed to try and be robust but are mutation is a random process with high variance!

::::

We could solve this challenge using a more fine-grained scheme like cg/wgMLST (as discussed in the previous module) but we are going to use `poppunk` in this lab.

`poppunk` is a rapid k-mer based genome clustering tool that groups genomes together based on both their core and accessory genome distances.  This allows differential clustering of similar genomes which have acquired novel plasmids and so on.  

The developers of poppunk provide some pre-computed databases (although it is easy to create your own) for different species which are available [here](https://www.bacpop.org/poppunk-databases/).

We have already downloaded a reference database for you, so all you have to do is prepare a 2-column file `genomes.txt` which has a series of names in the first column and the path to the related genome assembly in the other.
We can do this using a quick bash one-line loop:

```bash
for i in ../assemblies/*.fa; do isolate=$(echo $i | cut -d '/' -f3 | cut -d '.' -f1); echo -e "$isolate\t$i" >> genomes.txt; done
```

Then we can run the following to get poppunk cluster assignments:

```bash
poppunk_assign --db ~/CourseData/module4/staphylococcus_aureus_v1_full --query genomes.txt --output poppunk --threads 4
```

Now download/inspect `poppunk/poppunk_clusters.csv` file 

**Which genomes does this analysis suggest should be excluded?  Do they match the MLST results?**

:::: {.callout type="green" title="Answer" collapsible="true"}

Almost all samples other than P27-28 and P30-33 are assigned to different clusters. This matches the singleton STs for the MLST and the ST22 group but the ST772 and ST2371 have been clustered together.  If we look carefully at the MLST profile for these STs in `mlst.tsv` we can see some overlap in alleles but not that many.  As we aren't sure what this means for now, let's drop the unrelated clusters P27-P28 and P30-P33 and continue with our analysis 

::::

<a name="snp"></a>

### SNP Analysis

Now that we have eliminated some isolates that are unlikely to be connected to our main outbreak we can do a deeper analysis of the evolutionary relationships between our isolates.  For this we are going to perform a phylogenetic analysis. There are several way this could be done: 

- Inferring and aligning the core genome of our isolates by running a tool like `panaroo` on the genome assembly annotation files (generated with `prokka` or `bakta`).
- Mapping individual reads against a reference genome (e.g., a standard external reference or the suspected outbreak index case) with a tool like `snippy`.
- Mapping split-kmer distance from a reference genome using SKA2

**Why might we want to use the suspected index case as our reference genome?**

:::: {.callout type="green" title="Answer" collapsible="true"}

To maximise the number of SNPs we can detect by using a reference as close as possible to our other genomes

::::

For this lab, we are going to do the last option using a complete high quality reference genome generated from this outbreak subsequent to the original manuscript: SASCBU26

First let's generate the input file for SKA using the poppunk results

```bash
cd ~/workspace/module4; mkdir -p ska_phylogeny; cd ska_phylogeny
paste <(grep "3$" ../outbreak_cluster_identification/poppunk/poppunk_clusters.csv | cut -d, -f1) <(grep "3$" outbreak_cluster_identification/poppunk/poppunk_clusters.csv | cut -d, -f1 | sed 's/^/../assemblies\//g' | sed 's/$/.fa/g') > ska_input
echo -e "HO50960412\t../HO50960412_reference.fasta" >> ska_input
```

Now we need to generate an SKA index:

```bash
mkdir -p ska
ska build -f ska_input -k 31 -o ska/ska_index --threads 4
```

Then map these split k-mers against the reference:

```bash
ska map -o ska/ska.aln --ambig-mask --threads 4 SASCBU26_reference.fna ska/ska_index.skf
```

This gives us an alignment but due to the rate of recombination in many bacteria we typically want to try and remove remove recombination from the alignment.
There are several tools that can help us do this (`verticall`, `ClonalFrameML`, `gubbins`) and today we are going to use gubbins.

```bash
mkdir -p gubbins
run_gubbins.py --prefix gubbins/gubbins ska/ska.aln
mask_gubbins_aln.py --aln ska/ska.aln --gff gubbins.recombination_predictions.gff --out gubbins.masked.aln
```

Now that we have a masked alignment we can analyse the SNP network using GraphSNP to further refine our potential outbreak samples.

Download the aligned reference 

Navigate to [GraphSNP](https://graphsnp.fordelab.com/) in your browser and upload the new masked alignment and the metadata.

Then click the 3 horizontal lines on the top of the webpage and go to "Graph".

Create graph using the clustering analysis type and look at the structure of the SNP minimum spanning tree.

**Which genomes do you think you can eliminate from the immediate outbreak cluster?**

:::: {.callout type="green" title="Answer" collapsible="true"}
P34-38 and P29 - our earlier ST22 samples which MLST would have ruled out but poppunk convinced us to look a bit more closely at!
::::

Infer a phylogeny from the masked alignment:

```bash
iqtree -s gubbins.masked.aln
```

Download the generated `gubbins.masked.aln.treefile` and go to [microreact](https://microreact.org/upload).
Upload the tree and using the Tree Type button at the top right select radial/unrooted tree.

**Does the phylogeny show the same genomes as being outside the main outbreak cluster**

:::: {.callout type="green" title="Answer" collapsible="true"}
Yes
::::

<a name="trans"></a>

### Transmission Inference

Now we have refined our final set of suspected outbreak isolates we are going to perform some transmission analyses.  First we are going to use the SeqTrack method as implemented in graphSNP.

**Create a new gubbins-masked SKA alignment excluding the non-outbreak genomes (but retaining the HO50960412 reference genome). Hint: edit the ska_input file and ensure you update the output/prefixes for ska and gubbins.**

>! A pre-computed version is available at 

Download the `contextual_metadata.csv` and new masked alignment.

Navigate to [GraphSNP](https://graphsnp.fordelab.com/) in your browser and upload the new masked alignment and the metadata.

Then click the 3 horizontal lines on the top of the webpage and go to "Graph" but this time select analysis type "transmission".

Colour the nodes by host

**Which person is inferred to have infected the largest number of other patients?**

:::: {.callout type="green" title="Answer" collapsible="true"}
P2
::::

**Which baby was inferred to be infected by a parent?**

:::: {.callout type="green" title="Answer" collapsible="true"}
P15
::::

Now let's try a more sophisticated transmission inference method using `transphylo`.

To do this we need to create a phylogeny and then infer the dates on the phylogeny, for this we are going to dip into R.

Navigate to the instance RStudio Server: http://xxx.uhn-hpc.ca:8080

```R
library(bactdating)
dist_tree <- ape::read.tree("~/workspace/module4/PATH_TO_FINAL_IQTREE.tre")
dist_tree <- ape::drop.tip(dist_tree, "HO50960412")
dates <- read.csv("~/CourseData/module4/contextual_data.csv") 
rownames(dates) <- dates$sample_id
dates <- lubridate::decimal_date(lubridate::ymd(dates[dist_tree$tip.label, "collection_date"]))
res <- roottotip(dist_tree, dates)
res <- bactdate(ape::unroot(dist_tree),dates,nbIts=1000)
plot(res,'treeCI',show.tip.label = F)
ttree <- res$tree
```

Now we can use transphylo to perform transmission inference

```R
library(TransPhylo)
ptree<-ptreeFromPhylo(ttree,dateLastSample=max(dates))
```
